# Generated by Django 3.0.4 on 2020-10-24 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('task_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='ModelMap',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('level_1', models.CharField(max_length=64)),
                ('level_2', models.CharField(max_length=64)),
                ('level_3', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'modelmap',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=64, unique=True)),
                ('execute_status', models.CharField(max_length=64)),
                ('execute_result', models.CharField(max_length=64)),
                ('failed_reason', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=64)),
                ('file', models.ManyToManyField(to='plot.File')),
                ('level_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.ModelMap', to_field='level_3')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
